spring:
  profiles:
    active:
      - local

security:
  jwt:
    token:
      secret-key: kksangdolbabokksangdolbabokksangdolbabokksangdolbabokksangdolbabokksangdolbabo
      expire-length: 3600000

app:
  firebase-config-file: serviceAccountKey.json


url:
  moim: /moim
  chat: /chat
  chatroom: /chatting-room