spring:
  datasource:
    master:
      hikari:
        username: ${MASTER_MYSQL_USERNAME}
        password: ${MASTER_MYSQL_PASSWORD}
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: ${MASTER_MYSQL_URL}
    slave:
      hikari:
        username: ${SLAVE_MYSQL_USERNAME}
        password: ${SLAVE_MYSQL_PASSWORD}
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: ${SLAVE_MYSQL_URL}

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false

security:
  jwt:
    token:
      secret-key: ${JWT_SECRET_KEY}
      expire-length: ${JWT_EXPIRE_LENGTH}

url:
  base: https://mouda.site

oauth:
  kakao:
    redirect-uri: https://mouda.site/oauth/kakao
  google:
    client-secret: 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
    redirect-uri: https://mouda.site/oauth/google
  apple:
    redirect-uri: https://mouda.site/oauth/apple

aws:
  region:
    static: ap-northeast-2
  s3:
    bucket: arn:aws:s3:::techcourse-project-2024/mouda/prod/profile/
    prefix: https://dev.mouda.site/
