spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

url:
  base: https://dev.mouda.site

oauth:
  kakao:
    redirect-uri: https://dev.mouda.site/kakao-o-auth
  apple:
    redirect-uri: https://dev.mouda.site/apple-o-auth
